# .github/workflows/optimize.yml

name: SVG Optimization
on:
  push:
    branches:
      - main

# The minimum required permissions
permissions:
  contents: write

jobs:
  svgs:
    name: SVGs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Optimize SVGs
        uses: ericcornelissen/svgo-action@v3
        id: svgo
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
      - name: Commit optimizations
        uses: stefanzweifel/git-auto-commit-action@v4
        if: ${{steps.svgo.outputs.DID_OPTIMIZE}}
        with:
          commit_message: SVGOptimized.
